### ISSUE TITLE
Cannot download processed data

### ISSUE THREAD

**Issue by trydonot** [liujin0/SDnet#1]
Hi,

I tried to download the data but Baidu is not available in my country.
could you provide another link or send me data, please?

Thank you!

**Comment by liujin0** [comment]
Hi, thanks for your interests. The datasets are available at [google drive](https://drive.google.com/drive/folders/1oFJQJt_Gne22I7tOYpfu9A0ABEuFsIDS).

**Comment by trydonot** [comment]
Thank you!
